### ISSUE TITLE
Edit button redirects to wrong branch

### ISSUE THREAD

**Issue by m1raynee** [DisnakeDev/guide#4]
![image](https://user-images.githubusercontent.com/71838742/140867591-c0871ca4-de36-4ded-95ad-65742b55ca6c.png)
This button on https://guide.disnake.dev/ redirects to https://github.com/DisnakeDev/disnake/edit/master/docs/index.md
but it must be https://github.com/DisnakeDev/disnake/edit/main/docs/index.md

**Comment by abhigyantrips** [comment]
> This button on https://guide.disnake.dev/ redirects to https://github.com/DisnakeDev/disnake/edit/master/docs/index.md but it must be https://github.com/DisnakeDev/disnake/edit/main/docs/index.md

That button currently seems to be redirecting to the disnake repo and not the guide repo - because the `repo_url` mentioned for the top-right widget points to disnake.

This should be as easy as a yaml setting, will fix in next commit.

**Comment by abhigyantrips** [comment]
Currently just done a hotfix by hiding the edit button, so that no one uses it. :P 

The issue is that the `repo_url` currently points to the repo of the `disnake` library, and not the repo of the guide. So, the `edit_uri` tries to redirect you to the file, thinking that it exists in disnake. ;-;

Anyway, I've found a few plugins that introduce an `edit_url` option, which could fix this in the future. Until then, the edit button will remain hidden.
